#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Update dotly to the latest stable release
##?
##? Usage:
##?    update
docs::parse "$@"

cd "$DOTFILES_PATH"
git submodule update --init --remote modules/dotly

dot shell zsh reload_completions

output::answer '✅ dotly updated to the latest version'
